### ISSUE TITLE
inconsistency with css-loader

### ISSUE THREAD

**Issue by deanshub** [css-modules/generic-names#8]
the regex at [this line](https://github.com/css-modules/generic-names/blob/master/index.js#L44) breaks consistency with css-loader generation [getLocalIdent](https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L52)

the test case is `@` in node modules, scoping packages is getting popular and when we use the same parameters (localindentname, hashprefix,...) with requiring css from a node module that has `@` in it, `generic-names` replaces it with `-` but css-loader leaves it as `@`

That's because, `\u00A0-\uFFFF` doesn't contain `@`

**Comment by benmvp** [comment]
I'm having a similar problem, but w/ a [different line of code](https://github.com/css-modules/generic-names/blob/d57cb1c4dbf391fb68be9e5f38e68ad1d5a0f2d9/index.js#L34-L38). 😄 

[This PR](https://github.com/webpack-contrib/css-loader/pull/1121/files#diff-3274f1a37032fb0ae4e2823def0007c634e869ae0dfc304ff6a12c36513c3a52R64) changed the `content` being passed to `interpolateName` (in `loader-utils`) from including a plus `+` to including `\x00`. This is now in `css-loader` >= 4. However, `generic-names` still using `+` so there's now an inconsistency in how the class names are generated.

Given that this library is basically piggybacking on what webpack does, it seems like it should be updated to match. I already asked in `css-loader` and the change was intentional (https://github.com/webpack-contrib/css-loader/issues/1214).

The actual problem I'm having is with `babel-plugin-react-css-modules` which uses this package to generate the class names. See: https://github.com/gajus/babel-plugin-react-css-modules/issues/291

**Comment by benmvp** [comment]
@evilebottnawi is this something that can be changed here then?

**Comment by alexander-akait** [comment]
Why do you need `generic-names`?

**Comment by benmvp** [comment]
@evilebottnawi - `babel-plugin-react-css-modules` [uses `generic-names`](https://github.com/gajus/babel-plugin-react-css-modules/blob/91c8e9b9b272e1d16c756f7e865fdbf94dec2075/src/requireCssModule.js#L106-L108) in order to generate its scoped names. And since `generic-names` no longer uses the same format as `css-loader` v4+ ([see above](https://github.com/css-modules/generic-names/issues/8#issuecomment-714811620)), `babel-plugin-react-css-modules` is broken with `css-loader` v4+.

Here's the open issue: https://github.com/gajus/babel-plugin-react-css-modules/issues/291

**Comment by alexander-akait** [comment]
@benmvp You can send a PR

**Comment by alexander-akait** [comment]
Just copy logic from css-loader to here

**Comment by benmvp** [comment]
Cool, that was my plan, but wanted to make sure you were ok with it.

**Comment by alexander-akait** [comment]
:+1:
